export interface limitsData {
  dev?: boolean,
  persistence?: boolean,
  frontEndPage?: boolean,
  showFullApi?: boolean,
  setLimitItems?: boolean,
  setLimitPages?: boolean,
  limitItems?: number,
  limitPages?: number,
  setLang?: boolean,
  chooseLang?: string,
  setGenre?: boolean,
  setYear?: boolean,
  chooseGenreRef?: number | string,
  choseYear?: string,
}