export const Genres = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 10770, name: "TV Movie" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" }
];

export const Languages = [
  { iso_639_1: "xx", english_name: "No Language", name: "No Language" },
  { iso_639_1: "aa", english_name: "Afar", name: "" },
  { iso_639_1: "af", english_name: "Afrikaans", name: "Afrikaans" },
  { iso_639_1: "ak", english_name: "Akan", name: "" },
  { iso_639_1: "an", english_name: "Aragonese", name: "" },
  { iso_639_1: "as", english_name: "Assamese", name: "" },
  { iso_639_1: "av", english_name: "Avaric", name: "" },
  { iso_639_1: "ae", english_name: "Avestan", name: "" },
  { iso_639_1: "ay", english_name: "Aymara", name: "" },
  { iso_639_1: "az", english_name: "Azerbaijani", name: "Azərbaycan" },
  { iso_639_1: "ba", english_name: "Bashkir", name: "" },
  { iso_639_1: "bm", english_name: "Bambara", name: "Bamanankan" },
  { iso_639_1: "bn", english_name: "Bengali", name: "বাংলা" },
  { iso_639_1: "bi", english_name: "Bislama", name: "" },
  { iso_639_1: "bo", english_name: "Tibetan", name: "" },
  { iso_639_1: "bs", english_name: "Bosnian", name: "Bosanski" },
  { iso_639_1: "br", english_name: "Breton", name: "" },
  { iso_639_1: "ca", english_name: "Catalan", name: "Català" },
  { iso_639_1: "cs", english_name: "Czech", name: "Český" },
  { iso_639_1: "ch", english_name: "Chamorro", name: "Finu' Chamorro" }
];
